# Generated by Django 4.1.13 on 2024-08-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.TextField(max_length=70)),
                ('currency_name', models.TextField()),
                ('cash_buying', models.DecimalField(decimal_places=6, max_digits=14)),
                ('cash_selling', models.DecimalField(decimal_places=6, max_digits=14)),
            ],
        ),
    ]
