# Generated by Django 4.1.13 on 2024-08-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='currency_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='currency_name',
            field=models.CharField(max_length=10),
        ),
    ]
